(function () {
  'use strict';

  window.LantingCatalog = {
    pages: {
      '../pages/01.html': { id: '01', title: '系统公告' },
      '../pages/02.html': { id: '02', title: '检索帮助' },
      '../pages/03.html': { id: '03', title: '员工档案：沈屿' },
      '../pages/04.html': { id: '04', title: '考勤记录' },
      '../pages/05.html': { id: '05', title: '夜班日志' },
      '../pages/06.html': { id: '06', title: '样本 M-027' },
      '../pages/07.html': { id: '07', title: '许文兰档案' },
      '../pages/08.html': { id: '08', title: '访客登记' },
      '../pages/09.html': { id: '09', title: '监控缺失' },
      '../pages/10.html': { id: '10', title: '管理员账号说明' },
      '../pages/11.html': { id: '11', title: '2019关停公告' },
      '../pages/12.html': { id: '12', title: '守望者制度' },
      '../pages/13.html': { id: '13', title: '2026改档记录' },
      '../pages/14.html': { id: '14', title: '二维码残片' },
      '../pages/15.html': { id: '15', title: '沈屿私信' },
      '../pages/16.html': { id: '16', title: '虚拟巡房' },
      '../pages/17.html': { id: '17', title: '住户名单' },
      '../pages/18.html': { id: '18', title: '慧忆汤' },
      '../pages/19.html': { id: '19', title: '周德明日记' },
      '../pages/20.html': { id: '20', title: '林晚晴笔记' },
      '../pages/21.html': { id: '21', title: '7号楼异常' },
      '../pages/22.html': { id: '22', title: '7号楼平面图' },
      '../pages/23.html': { id: '23', title: '监控室门禁' },
      '../pages/24.html': { id: '24', title: '监控转录' },
      '../pages/25.html': { id: '25', title: '隐藏监控帧' },
      '../pages/26.html': { id: '26', title: '通话转写' },
      '../pages/27.html': { id: '27', title: '沈屿物品' },
      '../pages/28.html': { id: '28', title: '慧忆生物入口' },
      '../pages/29.html': { id: '29', title: '合作合同' },
      '../pages/30.html': { id: '30', title: '慧忆汤说明' },
      '../pages/31.html': { id: '31', title: '程帆邮件' },
      '../pages/32.html': { id: '32', title: '方案B记录' },
      '../pages/33.html': { id: '33', title: '博客引导' },
      '../pages/34.html': { id: '34', title: '给调查者' },
      '../pages/35.html': { id: '35', title: '街景谜题' },
      '../pages/36.html': { id: '36', title: '北门仓库' },
      '../pages/37.html': { id: '37', title: '守望者守则' },
      '../pages/38.html': { id: '38', title: '顾临川自白' },
      '../pages/39.html': { id: '39', title: '烧档条件' },
      '../pages/40.html': { id: '40', title: '夜班真相' },
      '../pages/41.html': { id: '41', title: '7-302状态' },
      '../pages/42.html': { id: '42', title: '沈攸独白' },
      '../pages/43.html': { id: '43', title: '我该怎么办' },
      '../pages/44.html': { id: '44', title: '结局：公开' },
      '../pages/45.html': { id: '45', title: '结局：烧掉' },
      '../pages/ex01.html': { id: 'EX01', title: '源码彩蛋' },
      '../pages/ex02.html': { id: 'EX02', title: '家属帖摘录' },
      '../pages/ex03.html': { id: 'EX03', title: '杜姐口述' },
      '../pages/ex04.html': { id: 'EX04', title: '马慧珍' },
      '../pages/ex05.html': { id: 'EX05', title: '结局：守望者' },
      '../external/huiyi-blog/index.html': { id: 'BLG', title: '帆影笔记' },
      '../external/huiyi-blog/post1.html': { id: 'BLG1', title: '博文：记忆可以备份吗' },
      '../external/huiyi-blog/post2.html': { id: 'BLG2', title: '博文：死人在档案里活着' },
      '../external/huiyi-blog/post3.html': { id: 'BLG3', title: '博文：北门' },
      '../external/huiyi-blog/post4.html': { id: 'BLG4', title: '博文：给调查者' },
      '../external/tieba-mirror.html': { id: 'EX02', title: '贴吧镜像' }
    },
    loginHints: [
      { need: '../pages/03.html', text: '照护员：员工姓名拼音（如沈屿 → shenyu），密码与账号相同。' },
      { need: '../pages/20.html', text: '护士长：账号 gulinchuan，密码为离职年+院名缩写（GLC2019）。' },
      { need: '../pages/29.html', text: '外包顾问：账号 huiyi，访客密钥 HY-visitor。' }
    ]
  };
})();
